# for starmap background, specified with -bg=1 flag

---
size: 1024
scale: 0.007
levels: 8
contrast: 1.0

seed: 56
x: 512
xs: 4
gradmax: 256
persistance: 0.5
lacunarity: 2
octaves: 8

gradfile: ./assets/starfield/gradients/heightmap_gradient_07.png
